services:
  app:
    network_mode: "host"
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MILVUS_HOST=localhost
      - MILVUS_PORT=19530
      - MONGODB_URI=mongodb://localhost:27017
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    depends_on:
      - milvus
      - mongodb
    volumes:
      - ./:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  milvus:
    network_mode: "host"
    image: milvusdb/milvus:v2.3.3
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_USE_EMBED=true
      - COMMON_STORAGETYPE=local
    volumes:
      - milvus_data:/var/lib/milvus

  mongodb:
    network_mode: "host"
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  stockfish:
    network_mode: "host"
    image: localhost/stockfish:local
    ports:
      - "8080:8080"

  frontend-angular:
    network_mode: "host"
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - app
    volumes:
      - ./frontend-angular:/app
    command: sh -c "npm install && ng serve --host 0.0.0.0 --port 4200"

volumes:
  milvus_data:
  mongodb_data:

